menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/smartkn
    About: /about/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
# disqus: 
# duoshuo:

# Analytics
# google-analytics:
ga: UA-114814365-1

# Copyright Infomation
startyear: 2018
